### ISSUE TITLE
Blender stutters when running filtering by portal entity

### ISSUE THREAD

**Issue by igro45** [Sollumz/Sollumz#801]
When I go into sorting entities by portals, a problem arises.... My blender starts to go crazy and stutter.... What could this be caused by?
https://streamable.com/3puef2

**Comment by Rigonkmalk** [comment]
**Blender version** : 3.6.4

**Sollumz version** : last pull on main branch

**What is the issue you're having?**

It's a huge project ( about 28 rooms ) and about 2000+ props, I have some slow on export the ytyp ( seems normal, because of the numbers of props ).

But when I tried to change the filter to "Portal" I'm stuck in a loop of blender not responding.

**What are you trying to do?**

Trying to change the Filter By in the MLO menu to Portal.

**Any errors or warnings? (Post screenshot below) :**

no

**Files to reproduce the problem (if applicable)**

Private project, if needed I can give the blend file and the fiveM ressources.

Video in the help channel : [https://discord.com/channels/899043946142003240/1163127104053989467](https://discord.com/channels/899043946142003240/1163127104053989467)

**Comment by alexguirre** [comment]
Sollumz rebuilds the list of valid portals/rooms multiple times per entity to do the filtering each time the UI needs to be redrawn. That seems to be causing the performance issue here, and, of course, it only gets worse the more entities you add.
